force-app/main/default/objects/DynamicActionConfig__c/DynamicActionConfig__c.object-meta.xml
<CustomObject>
    <label>Dynamic Action Config</label>
    <pluralLabel>Dynamic Action Config</pluralLabel>
    <nameField>
        <type>Text</type>
        <label>Setting Name</label>
    </nameField>
    <customSettingsType>Hierarchy</customSettingsType>
</CustomObject>

force-app/main/default/objects/DynamicActionConfig__c/fields/EnableTelemetry__c.field-meta.xml
<CustomField>
    <fullName>EnableTelemetry__c</fullName>
    <label>Enable Telemetry</label>
    <type>Checkbox</type>
    <defaultValue>false</defaultValue>
</CustomField>

force-app/main/default/objects/PromptLog__c/PromptLog__c.object-meta.xml
<CustomObject>
    <label>Prompt Log</label>
    <pluralLabel>Prompt Logs</pluralLabel>
    <nameField>
        <label>Prompt Log Name</label>
        <type>AutoNumber</type>
        <displayFormat>PL-{0000}</displayFormat>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PromptTelemetry_Test.cls
@IsTest
private class PromptTelemetry_Test {
    @IsTest
    static void captureRespectsToggle() {
        // Disabled by default
        PromptTelemetry.capture('Goal', null, 'response');
        System.assertEquals(0, [SELECT COUNT() FROM PromptLog__c], 'Telemetry should be disabled by default.');

        DynamicActionConfig__c setting = DynamicActionConfig__c.getInstance();
        if (setting == null) {
            setting = new DynamicActionConfig__c();
        }
        setting.SetupOwnerId = UserInfo.getOrganizationId();
        setting.EnableTelemetry__c = true;
        upsert setting;

        LLMClientGateway.LLMRequest request = new LLMClientGateway.LLMRequest();
        request.model = 'test-model';
        request.prompt = 'prompt';

        PromptTelemetry.capture('Goal', request, 'response');
        System.assertEquals(1, [SELECT COUNT() FROM PromptLog__c], 'Telemetry should insert when enabled.');
    }
}